In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
import requests
import json
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
data = Path('./Resources/DataProcessingExtractFile-RawData.csv')
df = pd.read_csv(data)
df.head(10)

Diabetes_Status  HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0                1     1.0       1.0        1.0          4     1.0     0.0   
1                1     0.0       0.0        0.0          3     1.0     0.0   
2                1     1.0       1.0        1.0          3     0.0     0.0   
3                1     1.0       0.0        1.0          3     0.0     0.0   
4                1     1.0       1.0        1.0          2     0.0     0.0   
5                1     1.0       1.0        1.0          3     1.0     0.0   
6                1     1.0       0.0        1.0          4     1.0     0.0   
7                1     1.0       1.0        1.0          3     1.0     0.0   
8                2     1.0       1.0        1.0          4     1.0     0.0   
9                1     0.0       0.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   
5                   0.0           1.0     1.0  ...            1.0   
6                   0.0           0.0     0.0  ...            1.0   
7                   0.0           1.0     0.0  ...            1.0   
8                   1.0           0.0     1.0  ...            1.0   
9                   0.0           0.0     0.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   
5          0.0      2.0                    1                      1       0.0   
6          0.0      3.0                    1                      3       0.0   
7          0.0      3.0                    1                      1       1.0   
8          0.0      5.0                    6                      6       1.0   
9          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  
5  1.0  10.0        6.0     8.0  
6  0.0   9.0        6.0     7.0  
7  0.0  11.0        4.0     4.0  
8  0.0   9.0        5.0     1.0  
9  1.0   8.0        4.0     3.0  

[10 rows x 22 columns]

In [19]:
# Random Forest Model

X = df.copy()
X = df.drop(df.columns[[0]], axis=1)
X.head()

HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0     1.0       1.0        1.0          4     1.0     0.0   
1     0.0       0.0        0.0          3     1.0     0.0   
2     1.0       1.0        1.0          3     0.0     0.0   
3     1.0       0.0        1.0          3     0.0     0.0   
4     1.0       1.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  AnyHealthcare  \
0                   0.0           0.0     0.0      1.0  ...            1.0   
1                   0.0           1.0     0.0      0.0  ...            0.0   
2                   0.0           0.0     1.0      0.0  ...            1.0   
3                   0.0           1.0     1.0      1.0  ...            1.0   
4                   0.0           1.0     1.0      1.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  

[5 rows x 21 columns]

In [20]:
y = df["Diabetes_Status"].ravel()
y[:5]

array([1, 1, 1, 1, 1])

In [21]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [22]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [23]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [24]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [25]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
predictions

array([1, 1, 1, ..., 1, 2, 2])

In [26]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0        50729         2619
Actual 1         7783         2289

In [27]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.8359823399558499

In [28]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        50729         2619
Actual 1         7783         2289

Accuracy Score : 0.8359823399558499
Classification Report
              precision    recall  f1-score   support

           1       0.87      0.95      0.91     53348
           2       0.47      0.23      0.31     10072

    accuracy                           0.84     63420
   macro avg       0.67      0.59      0.61     63420
weighted avg       0.80      0.84      0.81     63420



In [29]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.04875144, 0.03010365, 0.00483168, 0.05415876, 0.04118793,
       0.01550216, 0.02162988, 0.03225683, 0.04075334, 0.03322791,
       0.00961914, 0.01093706, 0.01944013, 0.08592286, 0.04363913,
       0.051591  , 0.02900203, 0.03545584, 0.16603811, 0.0924393 ,
       0.13351183])

In [30]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.166038111219324, 'Age'),
 (0.13351182864792496, 'Income'),
 (0.0924393012517978, 'Education'),
 (0.08592285964444238, 'GenHlth'),
 (0.05415876112148073, 'BMI_Range'),
 (0.05159100094189288, 'Physical_Health_Range'),
 (0.048751444402072325, 'HighBP'),
 (0.04363912785099077, 'Mental_Health_Range'),
 (0.04118792979156528, 'Smoker'),
 (0.040753338226660954, 'Fruits'),
 (0.0354558383156238, 'Sex'),
 (0.033227905566415514, 'Veggies'),
 (0.032256831910182235, 'PhysActivity'),
 (0.03010364575825829, 'HighChol'),
 (0.029002033614323103, 'DiffWalk'),
 (0.02162987888406562, 'HeartDiseaseorAttack'),
 (0.019440125448018836, 'NoDocbcCost'),
 (0.015502158759623465, 'Stroke'),
 (0.010937061769505315, 'AnyHealthcare'),
 (0.009619137016599949, 'HvyAlcoholConsump'),
 (0.004831679859231867, 'CholCheck')]

In [31]:
pickle.dump(rf_model, open('model.pkl','wb'))