In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
import requests
import json
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [36]:
data = Path('./Resources/DataProcessingExtractFile-SampleTwo.csv')
df = pd.read_csv(data)
df.head(10)

Diabetes_Status  HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0                1     1.0       1.0        1.0          4     1.0     0.0   
1                1     0.0       0.0        0.0          3     1.0     0.0   
2                1     1.0       1.0        1.0          3     0.0     0.0   
3                1     1.0       0.0        1.0          3     0.0     0.0   
4                1     1.0       1.0        1.0          2     0.0     0.0   
5                1     1.0       1.0        1.0          3     1.0     0.0   
6                1     1.0       0.0        1.0          4     1.0     0.0   
7                1     1.0       1.0        1.0          3     1.0     0.0   
8                2     1.0       1.0        1.0          4     1.0     0.0   
9                1     0.0       0.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   
5                   0.0           1.0     1.0  ...            1.0   
6                   0.0           0.0     0.0  ...            1.0   
7                   0.0           1.0     0.0  ...            1.0   
8                   1.0           0.0     1.0  ...            1.0   
9                   0.0           0.0     0.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   
5          0.0      2.0                    1                      1       0.0   
6          0.0      3.0                    1                      3       0.0   
7          0.0      3.0                    1                      1       1.0   
8          0.0      5.0                    6                      6       1.0   
9          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  
5  1.0  10.0        6.0     8.0  
6  0.0   9.0        6.0     7.0  
7  0.0  11.0        4.0     4.0  
8  0.0   9.0        5.0     1.0  
9  1.0   8.0        4.0     3.0  

[10 rows x 22 columns]

In [37]:
# Random Forest Model

X = df.copy()
X = df.drop(df.columns[[0]], axis=1)
X.head()

HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0     1.0       1.0        1.0          4     1.0     0.0   
1     0.0       0.0        0.0          3     1.0     0.0   
2     1.0       1.0        1.0          3     0.0     0.0   
3     1.0       0.0        1.0          3     0.0     0.0   
4     1.0       1.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  AnyHealthcare  \
0                   0.0           0.0     0.0      1.0  ...            1.0   
1                   0.0           1.0     0.0      0.0  ...            0.0   
2                   0.0           0.0     1.0      0.0  ...            1.0   
3                   0.0           1.0     1.0      1.0  ...            1.0   
4                   0.0           1.0     1.0      1.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  

[5 rows x 21 columns]

In [38]:
y = df["Diabetes_Status"].ravel()
y[:5]

array([1, 1, 1, 1, 1])

In [39]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y, 
                                                    random_state=78,
                                                    stratify=y)

In [40]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [41]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [42]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [43]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
predictions

array([2, 1, 1, ..., 1, 1, 2])

In [44]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0        32881         3085
Actual 1         7433         1874

In [45]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.767676098336757

In [46]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        32881         3085
Actual 1         7433         1874

Accuracy Score : 0.767676098336757
Classification Report
              precision    recall  f1-score   support

           1       0.82      0.91      0.86     35966
           2       0.38      0.20      0.26      9307

    accuracy                           0.77     45273
   macro avg       0.60      0.56      0.56     45273
weighted avg       0.73      0.77      0.74     45273



In [47]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.04217697, 0.02901382, 0.00590753, 0.05186766, 0.04125038,
       0.01533614, 0.02078036, 0.03659019, 0.04146224, 0.03449456,
       0.00974246, 0.01104591, 0.02039371, 0.07412433, 0.04465706,
       0.05452639, 0.02423868, 0.03359857, 0.16901412, 0.0985342 ,
       0.14124472])

In [48]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.16901412491228535, 'Age'),
 (0.14124471849932682, 'Income'),
 (0.09853420486840132, 'Education'),
 (0.07412432928053321, 'GenHlth'),
 (0.05452638677357408, 'Physical_Health_Range'),
 (0.05186765799634323, 'BMI_Range'),
 (0.04465705842270284, 'Mental_Health_Range'),
 (0.042176974669801165, 'HighBP'),
 (0.04146224486943719, 'Fruits'),
 (0.041250377581548245, 'Smoker'),
 (0.03659018502268954, 'PhysActivity'),
 (0.034494557678877345, 'Veggies'),
 (0.033598574121431794, 'Sex'),
 (0.02901382096930928, 'HighChol'),
 (0.02423868293971278, 'DiffWalk'),
 (0.020780360775709147, 'HeartDiseaseorAttack'),
 (0.020393705444469945, 'NoDocbcCost'),
 (0.015336143853370919, 'Stroke'),
 (0.01104590927248782, 'AnyHealthcare'),
 (0.009742455256223559, 'HvyAlcoholConsump'),
 (0.00590752679176444, 'CholCheck')]

In [49]:
pickle.dump(rf_model, open('model_2.pkl','wb'))

In [50]:
array = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]

In [51]:
y_pred = rf_model.predict([array])
y_pred

array([1])