In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
data = Path('../results/diabetes_raw_data.csv')
df = pd.read_csv(data)
df.head(10)

Unnamed: 0  Diabetes_Status  HighBP  HighChol  CholCheck  BMI_Range  \
0           0                1     1.0       1.0        1.0          4   
1           1                1     0.0       0.0        0.0          3   
2           2                1     1.0       1.0        1.0          3   
3           3                1     1.0       0.0        1.0          3   
4           4                1     1.0       1.0        1.0          2   
5           5                1     1.0       1.0        1.0          3   
6           6                1     1.0       0.0        1.0          4   
7           7                1     1.0       1.0        1.0          3   
8           8                2     1.0       1.0        1.0          4   
9           9                1     0.0       0.0        1.0          2   

   Smoker  Stroke  HeartDiseaseorAttack  PhysActivity  ...  AnyHealthcare  \
0     1.0     0.0                   0.0           0.0  ...            1.0   
1     1.0     0.0                   0.0           1.0  ...            0.0   
2     0.0     0.0                   0.0           0.0  ...            1.0   
3     0.0     0.0                   0.0           1.0  ...            1.0   
4     0.0     0.0                   0.0           1.0  ...            1.0   
5     1.0     0.0                   0.0           1.0  ...            1.0   
6     1.0     0.0                   0.0           0.0  ...            1.0   
7     1.0     0.0                   0.0           1.0  ...            1.0   
8     1.0     0.0                   1.0           0.0  ...            1.0   
9     0.0     0.0                   0.0           0.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   
5          0.0      2.0                    1                      1       0.0   
6          0.0      3.0                    1                      3       0.0   
7          0.0      3.0                    1                      1       1.0   
8          0.0      5.0                    6                      6       1.0   
9          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  
5  1.0  10.0        6.0     8.0  
6  0.0   9.0        6.0     7.0  
7  0.0  11.0        4.0     4.0  
8  0.0   9.0        5.0     1.0  
9  1.0   8.0        4.0     3.0  

[10 rows x 23 columns]

In [3]:
# Linear Regression Model

y = df["Diabetes_Status"]
X = df.drop(columns="Diabetes_Status")

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y,
                                                    test_size=0.25)
X_train.shape

(190260, 22)

In [5]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200,
   random_state=1)

In [6]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [7]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            1       1
1            1       1
2            1       1
3            1       1
4            1       1
5            1       1
6            1       1
7            1       2
8            1       1
9            1       1
10           1       1
11           1       1
12           1       1
13           1       1
14           1       2
15           1       2
16           1       1
17           1       1
18           1       1
19           1       1

In [8]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8424156417533901


In [15]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[53426     0]
 [ 9994     0]]


In [17]:
print(f'confusion matrix:\n {confusion_matrix(y_test, y_pred)}')
print('===============================================\n')
print(classification_report(y_test, y_pred, zero_division=0))

confusion matrix:
 [[53426     0]
 [ 9994     0]]

              precision    recall  f1-score   support

           1       0.84      1.00      0.91     53426
           2       0.00      0.00      0.00      9994

    accuracy                           0.84     63420
   macro avg       0.42      0.50      0.46     63420
weighted avg       0.71      0.84      0.77     63420



In [10]:
# report = classification_report(y_test, y_pred)
# print(report)

              precision    recall  f1-score   support

           1       0.84      1.00      0.91     53426
           2       0.00      0.00      0.00      9994

    accuracy                           0.84     63420
   macro avg       0.42      0.50      0.46     63420
weighted avg       0.71      0.84      0.77     63420



C:\Users\kbrabec\Anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kbrabec\Anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kbrabec\Anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# # SVM Model ***NEEDS FIX

# y = df["Diabetes_Status"]
# X = df.drop(columns="Diabetes_Status")

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X,
#    y,  random_state=1, stratify=y, test_size=0.25)
# X_train.shape

# from sklearn.svm import SVC
# model = SVC(kernel='linear')

# model.fit(X_train, y_train)

# y_pred = model.predict(X_test)
# results = pd.DataFrame({
#    "Prediction": y_pred,
#    "Actual": y_test
# }).reset_index(drop=True)
# results.head()

# from sklearn.metrics import accuracy_score
# accuracy_score(y_test, y_pred)

# from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, y_pred)

# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_pred))

In [18]:
# Decision Tree

X = df.copy()
X = X.drop("Diabetes_Status", axis=1)
X.head()

Unnamed: 0  HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0           0     1.0       1.0        1.0          4     1.0     0.0   
1           1     0.0       0.0        0.0          3     1.0     0.0   
2           2     1.0       1.0        1.0          3     0.0     0.0   
3           3     1.0       0.0        1.0          3     0.0     0.0   
4           4     1.0       1.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [19]:
y = df["Diabetes_Status"].values
y[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [21]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(190260, 22)
(63420, 22)
(190260,)
(63420,)


In [22]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [23]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [24]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [25]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0        45804         7544
Actual 1         6689         3383

In [26]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.7755755282245348

In [28]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        45804         7544
Actual 1         6689         3383

Accuracy Score : 0.7755755282245348
Classification Report
              precision    recall  f1-score   support

           1       0.87      0.86      0.87     53348
           2       0.31      0.34      0.32     10072

    accuracy                           0.78     63420
   macro avg       0.59      0.60      0.59     63420
weighted avg       0.78      0.78      0.78     63420



In [29]:
# Random Forest Classifier
X = df.copy()
X = X.drop("Diabetes_Status", axis=1)
X.head()

Unnamed: 0  HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0           0     1.0       1.0        1.0          4     1.0     0.0   
1           1     0.0       0.0        0.0          3     1.0     0.0   
2           2     1.0       1.0        1.0          3     0.0     0.0   
3           3     1.0       0.0        1.0          3     0.0     0.0   
4           4     1.0       1.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [30]:
y = df["Diabetes_Status"].ravel()
y[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [31]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [32]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [33]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [34]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [35]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [36]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0        51292         2056
Actual 1         8041         2031

In [37]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.8407915484074424

In [38]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        51292         2056
Actual 1         8041         2031

Accuracy Score : 0.8407915484074424
Classification Report
              precision    recall  f1-score   support

           1       0.86      0.96      0.91     53348
           2       0.50      0.20      0.29     10072

    accuracy                           0.84     63420
   macro avg       0.68      0.58      0.60     63420
weighted avg       0.81      0.84      0.81     63420



In [39]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.27482374, 0.04116389, 0.0270793 , 0.00368627, 0.04453826,
       0.02900981, 0.01175795, 0.01685998, 0.02328829, 0.0288799 ,
       0.02242228, 0.00739432, 0.00815935, 0.01407693, 0.06934518,
       0.03091681, 0.03768519, 0.02288717, 0.02498528, 0.11054128,
       0.06203465, 0.08846416])

In [40]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.27482374364989254, 'Unnamed: 0'),
 (0.1105412817343995, 'Age'),
 (0.08846415844376737, 'Income'),
 (0.06934517528425119, 'GenHlth'),
 (0.062034645052552365, 'Education'),
 (0.044538257650013804, 'BMI_Range'),
 (0.04116388817861584, 'HighBP'),
 (0.037685192295919163, 'Physical_Health_Range'),
 (0.03091681288679535, 'Mental_Health_Range'),
 (0.029009810096028637, 'Smoker'),
 (0.028879903608129146, 'Fruits'),
 (0.02707930209782775, 'HighChol'),
 (0.024985282746017672, 'Sex'),
 (0.023288293392525392, 'PhysActivity'),
 (0.022887174633735363, 'DiffWalk'),
 (0.022422278713136977, 'Veggies'),
 (0.01685998008286824, 'HeartDiseaseorAttack'),
 (0.014076929445135318, 'NoDocbcCost'),
 (0.011757948691908632, 'Stroke'),
 (0.008159349448417024, 'AnyHealthcare'),
 (0.007394323302047011, 'HvyAlcoholConsump'),
 (0.0036862685660159025, 'CholCheck')]

In [42]:
# # Boosting Model
# X = df.copy()
# X = X.drop("Diabetes_Status", axis=1)
# y = df["Diabetes_Status"].values

In [43]:
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# X_train, X_test, y_train, y_test = train_test_split(X,
#    y, random_state=1)

In [44]:
# scaler = StandardScaler()
# X_scaler = scaler.fit(X_train)
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

In [45]:
# # NEEDS FIXING
# from sklearn.ensemble import GradientBoostingClassifier
# learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
# for learning_rate in learning_rates:
#    classifier = GradientBoostingClassifier(n_estimators=20,
#    learning_rate=learning_rate,
#    max_features=5,
#    max_depth=3,
#    random_state=0)
#    classifier.fit(X_train_scaled, y_train.ravel)
    
#    print("Learning rate: ", learning_rate)
#    print("Accuracy score (training): {0:.3f}".format(
#        classifier.score(
#            X_train_scaled,
#            y_train)))
#    print("Accuracy score (validation): {0:.3f}".format(
#        classifier.score(
#            X_test_scaled,
#            y_test)))

# classifier = GradientBoostingClassifier(n_estimators=20,
#    learning_rate=0.5, max_features=5, max_depth=3, random_state=0)

# classifier.fit(X_train_scaled, y_train)
# predictions = classifier.predict(X_test_scaled)

# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import accuracy_score
# from sklearn.metrics import classification_report
# acc_score = accuracy_score(y_test, predictions)
# print(f"Accuracy Score : {acc_score}")

# cm = confusion_matrix(y_test, predictions)
# cm_df = pd.DataFrame(
#    cm, index=["Actual 0", "Actual 1"],
#    columns=["Predicted 0", "Predicted 1"]
# )
# display(cm_df)

# print("Classification Report")
# print(classification_report(y_test, predictions))

TypeError: Singleton array array(<built-in method ravel of numpy.ndarray object at 0x00000221BD982990>,
      dtype=object) cannot be considered a valid collection.

In [ ]:
# Oversampling Model ???
# SMOTEENN Model ???